version: "3.8"

services:
  strapi:
    build: .
    container_name: strapi-app
    ports:
     - "1337:1337"
    volumes:
      - ./app:/srv/app
      - ./public/uploads:/srv/app/public/uploads
    environment:
      HOST: 0.0.0.0
      PORT: 1337
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: str@p1
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: mariadb:11.3
    container_name: strapi-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ssword
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: str@p1
    ports:
      - "3307:3306" 
    volumes:
      - db_stapi:/var/lib/mysql

volumes:
  db_stapi: